/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzgc_jni_NativeFunction */

#ifndef _Included_com_hzgc_jni_NativeFunction
#define _Included_com_hzgc_jni_NativeFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzgc_jni_NativeFunction
 * Method:    feature_extract
 * Signature: ([III)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_hzgc_jni_NativeFunction_feature_1extract
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_hzgc_jni_NativeFunction
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzgc_jni_NativeFunction_init
  (JNIEnv *, jclass);

/*
 * Class:     com_hzgc_jni_NativeFunction
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzgc_jni_NativeFunction_destory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
